### PR TITLE
add prettier and format code

### PR DESCRIPTION
**Pull request by Elecweb**
#3 

I try to write prettierrc.json (this file is for telling prettier how to format code) as how you write code in this repo. It'd be great if you can give me your feedback.

I also add files in this pull request that's formatted so that you can see how prettier format your files.

if you're ok with the prettier config, I'll add pre commit script to format code automatically

but first let's make sure if this prettier config is ok or not

### CODE REVIEW

**Comment by rdinicut** [comment]
Hi @Elecweb , thanks for you contribution.LGTM! Please add the pre commit script

**Comment by Elecweb** [comment]
@rdinicut Ok, I'll do it tonight : )

**Comment by Elecweb** [comment]
@rdinicut I've added prettier and rebase branch.

**Comment by Elecweb** [comment]
#4

**Pull request merged**
